// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwd15lGedwoSFvmbu98joYP67HsI-Mp9U',
    appId: '1:29197350664:web:c4676b5bebb87924735ebd',
    messagingSenderId: '29197350664',
    projectId: 'ici-process',
    authDomain: 'ici-process.firebaseapp.com',
    storageBucket: 'ici-process.firebasestorage.app',
    measurementId: 'G-WXGRTCY63T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3gCmTzS9u6VKQQK1vX_1ZuZqEclx1uWA',
    appId: '1:29197350664:android:9bbc19bff7a2941f735ebd',
    messagingSenderId: '29197350664',
    projectId: 'ici-process',
    storageBucket: 'ici-process.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2ZHdHfPKvAIUG6DPU6pwsB_xg-o-mOlI',
    appId: '1:29197350664:ios:dacbd9f9406baf63735ebd',
    messagingSenderId: '29197350664',
    projectId: 'ici-process',
    storageBucket: 'ici-process.firebasestorage.app',
    iosBundleId: 'com.example.iciProcess',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2ZHdHfPKvAIUG6DPU6pwsB_xg-o-mOlI',
    appId: '1:29197350664:ios:dacbd9f9406baf63735ebd',
    messagingSenderId: '29197350664',
    projectId: 'ici-process',
    storageBucket: 'ici-process.firebasestorage.app',
    iosBundleId: 'com.example.iciProcess',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwd15lGedwoSFvmbu98joYP67HsI-Mp9U',
    appId: '1:29197350664:web:78068f3ac21b2f5a735ebd',
    messagingSenderId: '29197350664',
    projectId: 'ici-process',
    authDomain: 'ici-process.firebaseapp.com',
    storageBucket: 'ici-process.firebasestorage.app',
    measurementId: 'G-W7EP99ZXB7',
  );
}
